### ISSUE TITLE
There is a problem with one or more of your inputs, please check and try again

### ISSUE THREAD

**Issue by tor888** [OutCast3k/coinbin#126]
Hello.What happen wirh my wallet GPcjmzVyVwwPWykniVAMw6jQrc3v7GsTPh ???
I can't login!

**Comment by OutCast3k** [comment]
That is not a bitcoin address and you are not very clear regarding your
issue.

On 13 Nov 2017 6:16 am, "tor888" <notifications@github.com> wrote:

Hello.What happen wirh my wallet Gpcjmzvyvwwpwyknivamw6jqrc3v7gstph ???
I can't login!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OutCast3k/coinbin/issues/126>, or mute the thread

**Comment by tor888** [comment]
This is BTG address!I generated him yestarday and use for mine BTG.!
Today i try sign and cannot login.MWhy?Wallet not work or what?

**Comment by OutCast3k** [comment]
I'm the lead developer of coinb.in 

I do not understand what you are saying. 

Coinb.in does not support BTG.
Coinb.in does not have a wallet to login for bitcoin gold either.

We can not help you.
