### ISSUE TITLE
"Missing Inputs"

### ISSUE THREAD

**Issue by D2301** [OutCast3k/coinbin#128]
Im not being allowed to send any transaction. Each one pops up saying Missing Inputs. Everything is entered in correctly nothing at all is missing. Please help

**Comment by OutCast3k** [comment]
Hi,

I've already replied to your email you sent, you need to provide the steps to reproduce the error and if possible provide screenshots because I can't tell where you are receiving that error exactly.

Thanks

**Comment by OutCast3k** [comment]
You are trying to spend an UNCONFIRMED dust input which our service doesn't see in the blockchain or mem pool and therefore doesn't accept it, it's been broadcasted for you via chian.so and blockcypher, the transactions are pending confirmation. They probably won't confirm because you've tried to spend unconfirmed dust transactions with a very low fee. If you stop trying to submit the transaction 15x an hour as you've stated it will eventually expire over a week from your last sumittion and then you'll be able to use your normal inputs again. Alternatively, you could try manually building the transaction with the tools we provide with out the dust inputs or even import your keys to another client
