### ISSUE TITLE
Transactions popping up with different errors each time 

### ISSUE THREAD

**Issue by D2301** [OutCast3k/coinbin#129]
Im trying to send a transaction out. everything is confirmed and i shouldnt be having any problems. First error was missing inputs, second was uneeded verification of transaction, third was minpool not met (there was a warning about a high fee when clicking submit. i know i met the min) none of the transactions i create will go through. ive tried over 15 times within the last hour. even tried broadcasting it on different websites but nothing.

**Comment by OutCast3k** [comment]
With out details of the hex encoded transaction and the exact corresponding error messages and the with out the steps to reproduce the errors it's nearly impossible for us to help, our code base does not contain these errors and they are coming from the bitcoin core client.

As explained via email, your transaction was accepted according to chain.so and blockcypher, most of your problems probably stem from the fact you keep resubmitting your transaction which contains unconfirmed dust inputs, with out a waiting for it to confirm.

At this point we are unable to help you, i would suggest making the transaction manually or importing your private keys to another client.

**Comment by OutCast3k** [comment]
You are trying to spend an UNCONFIRMED dust input which our service doesn't see in the blockchain or mem pool and therefore doesn't accept it, it's been broadcasted for you via chian.so and blockcypher, the transactions are pending confirmation. They probably won't confirm because you've tried to spend unconfirmed dust transactions with a very low fee. If you stop trying to submit the transaction 15x an hour as you've stated it will eventually expire over a week from your last sumittion and then you'll be able to use your normal inputs again. Alternatively, you could try manually building the transaction with the tools we provide with out the dust inputs or even import your keys to another client
