### ISSUE TITLE
exporting keys

### ISSUE THREAD

**Issue by D2301** [OutCast3k/coinbin#130]
Would you be able to tell me how to export my keys off of bitcoin.in please

**Comment by OutCast3k** [comment]
You simply click the great big keys button when you login.

Please use some common sense, this is a free project designed for advanced users, I understand you might be frustrated with your transaction but we are not in control of your coins, you are. 

You are trying to spend dust which our service doesn't accept, it's been broadcasted for you via chian.so and blockcypher, the transactions are pending confirmation. They probably won't confirm because you've tried to spend unconfirmed dust transactions with a very low fee. If you stop trying to submit the transaction 15x an hour as you've stated it will eventually expire over a week or so and you'll be able to use it again. Alternatively, you could try manually building the transaction with the tools we provide with our the dust inputs or even import your keys to another client.

Please do not raise any more tickets.
