### ISSUE TITLE
Wallet transaction create 5 outputs of 1 address?!

### ISSUE THREAD

**Issue by dealorde** [OutCast3k/coinbin#137]
I just made a transaction from my coinbin wallet (legacy).
I use coinbin more then 2 years now and never had this problem...
After few hours I checked if the transaction was confirmed and it wasn't!
When I looked up the TX, I discovered that the transaction size is 815 bytes ?!
The 815 Bytes was created by 5 times the input of the same address?!

How is this possible?! 
How can I avoid this?!

TX: 1c73a3fbfc8da992463d77d0f90417ee13a053fcec617c321c9ab1eeb963ab3b

![same-output](https://user-images.githubusercontent.com/35138343/34609473-2fc3f500-f21d-11e7-8de5-ca572deb3ac0.png)

**Comment by OutCast3k** [comment]
Hi,

Unfortunately, the bitcoin network is very busy at the moment, meaning a higher fee is required for faster processing times.

Your transaction is large because it has a lot of inputs, inputs are transaction data.

In future you can use the calculator tool https://coinb.in/#fees to calculate your fees. You can also click on the blue question mark next to the fees input value, it will tell you how many inputs and outputs you are trying to spend and predict a fee to process it promptly.

As it stands there isn't much you can do other than trying to do a CPFP transaction or a double spend.

To conclude these problems are not a fault of coinb.in but an unfortunate side effect of a busy network.

All the best.
