### ISSUE TITLE
unable to turn off  RBF for Timelocked txns

### ISSUE THREAD

**Issue by lizz-y** [OutCast3k/coinbin#193]
unable to turn off  RBF. Please fix it.

**Comment by Wowee0** [comment]
@panagiotos RBF is turned off by default.
I was able to make transactions with and without RBF.  
If you are still having an issue, could you explain with more detail?

**Comment by lizz-y** [comment]
@Wowee0 

RBF automatically turned off for normal txns but not for timelocked txn.

**Comment by lizz-y** [comment]
i checked a timelocked txn by turning off and on RBF at https://live.blockcypher.com/btc/decodetx/ and it always shows `"opt_in_rbf": true, `.

**Comment by Wowee0** [comment]
@lizz-y Here's a timelocked transaction made by coinbin on BTC testnet, tx#7d89b9821776ad1fef7aeb508209b470a5219591714bb59dfb15e43846ce1757.  Timelock script is "03c32818b1752103a51cec1cfe9844c9c3e9b536bea8edb22c1fef0af1b55b19dc197170a9e58567ac".  The TX does not have RBF turned on.  

Could you provide more information, and a testnet example, created by coinbin.

**Comment by Wowee0** [comment]
Documentation:
- https://medium.com/summa-technology/bitcoins-time-locks-27e0c362d7a1 - a good overview much more readable than the obtuse BIP documentation.
- https://bitcoin.stackexchange.com/questions/87372/what-does-the-sequence-in-a-transaction-input-mean - answer that comprehensively explores nSequence and how it has evolved since inception
- https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki - official spec OP_CHECKLOCKTIMEVERIFY.

**Comment by lizz-y** [comment]
Thank you very much for addressing the issue.
