### ISSUE TITLE
Compressed vs. uncompressed

### ISSUE THREAD

**Issue by FrancisPouliot** [OutCast3k/coinbin#29]
Would it be possible to have access to private key uncompressed in wallet?

**Comment by OutCast3k** [comment]
Hey,

Sorry for not replying to this suggestion sooner, I've been pretty busy at work, had my computer fail on me and then xmas.

Your address provided on screen when you log-in to the wallet section of coinb.in (http://coinb.in/#wallet) is a compressed address, there is no use to having a uncompressed key when the uncompressed address is not shown.

If you could explain why you think we need this feature im all ears, otherwise I don't see a point in adding it....

**Comment by FrancisPouliot** [comment]
what I meant was base58 wallet import format (so that the private key can we swept easily)

**Comment by OutCast3k** [comment]
If you want access to your private key on the wallet page, https://coinb.in/#wallet you much click the "keys" button below your address and qrcode. You will then see your key in a WIF format, and below it an encrypted WIF.

Hope this helps.
