### ISSUE TITLE
Won't let me send coins

### ISSUE THREAD

**Issue by thecapmamba** [OutCast3k/coinbin#41]
I try to send coins and it either says the payment was confirmed and it doesn't send them, has an error, or generates a green colored textid. Have never had such an issue, please help thanks.

**Comment by thecapmamba** [comment]
![screen shot 2016-01-19 at 8 52 56 pm](https://cloud.githubusercontent.com/assets/16788623/12437768/aa3e6946-beee-11e5-93a1-8c910d129001.png)

**Comment by Hannes1** [comment]
Same Problem here

**Comment by OutCast3k** [comment]
Seem to have missed this issue, sorry. Can you let me know your address if you are still experiencing it. If you dont want to make it public my email is outcast3k (at) gmail . com

**Comment by OutCast3k** [comment]
I've added an extra feature to coinbin in the latest update.

When a transaction fails to broadcast due to a server side issue, the signed transaction will be produced in a box below. You can take this transaction and use it to broadcast via another service provider and/or use it when contacting myself so I can inspect the issue further.

Thanks.
