### ISSUE TITLE
Confusion with transaction fee calculation

### ISSUE THREAD

**Issue by lleolin** [OutCast3k/coinbin#50]
I used the Transaction tool with a redeem script to generate a transaction. The wallet in question had about 5mBTC in it. I entered a small amount to send, without paying close attention to the transaction fee, which I wrongly assumed was being calculated as a percentage of the amount being sent.

The transaction fee seems to be the difference of the entered amount and the total amount in the wallet. This ended up being about 1mBTC sent to the destination address, but with a 4mBTC transaction fee, meaning most of the contents of the wallet ended up being the fee for the transaction. I'm _really_ glad I was toying with trivial amounts of BTC in this case, because something like 1BTC/4BTC would have been devastating.

I'm trying to understand this better. How much _should_ a transaction fee be relative to the amount being sent, and what's preventing a more nuanced calculation taking place? I'm coming from Electrum where I happily and stupidly accept the fee presented and don't have to think about it too hard. (I used coinbin because I couldn't figure out how to sign/send transactions from multisig wallets created outside of Electrum.)

I get that it's ultimately on me to make sure everything is set correctly, but the default in this case seem a bit "dangerous". The assumption that any amount not being sent is intended to be the transaction fee is a huge assumption to me; I'm spending a partial amount because I want to save the rest. If nothing else, a fee that eclipses the amount should give me a red flag, as should fees above a certain percentage of the amount. But ideally we could calculate an optimal fee for the given amount.

**Comment by myveryown** [comment]
the transaction fee is the input less the outputs - so you need to arrange your own change and ensure the transaction fee that then remains is sufficient to cover the size of the tx ..use https://bitcoinfees.21.co/ as a guide

**Comment by OutCast3k** [comment]
There is a fail safe for higher amounts. If you had chosen a fee greater than 0.01 your have received the following message:

-------
Warning High Fee!
Please be aware that you have created a transaction with what seems to be a very high fee of 0.01000000 BTC!

OK, I've got it!
-------

**Comment by dabura667** [comment]
Testing developer tools with real bitcoins when you don't have a good grasp on how everything works.

Not a good idea.

Luckily, it was only a few mBTC. Cheap lesson to learn. Some guy accidentally sent 200 BTC in a fee.

@OutCast3K Perhaps the warning should be based around satoshis/byte instead.

If we assume he sent a normal transaction, it would prolly be 260 bytes... So

0.004 * 1e8 / 260

That's 1538 satoshis / byte. (Looking at 21's fee estimation site, even during congestion the largest fees were 60-80 sat/byte to get into the next block.)

Instead of hard coding 0.01, how about:

(($("#inputs .row").length * 149) + ($("#recipients .row").length * 34) + 10) * 200 * 1e-8

This will give the BTC amount you should check if fee is above.

If this person was one input, one output, the calculation would warn him above 0.000386 BTC.

In fact, we could even query 21's fee api for "fastestFee" and multiply it by 2 for some wiggle room, and if 21 is not available hard code 200 sat/byte or something.

Either way, I think rather than only showing the warning limit, the modal should show in big red letters

1. Your current absolute estimated fee (that triggered the warning) (with a note that it is only an estimation)

I'm wondering if there's a smarter way to estimate the final byte size. We can estimate one ecdsa sig to be 74 bytes including the PUSH byte.

**Comment by lleolin** [comment]
The only way to fully understand how something works is to use it. Is there a better way to test besides using small amounts of BTC?

**Comment by dabura667** [comment]
Testnet
