### ISSUE TITLE
Create transaction doesn't work (from local source)

### ISSUE THREAD

**Issue by the-schnibble** [OutCast3k/coinbin#68]
Unable to load address inputs if wallet opened from local copy. It shows the message "Retrieved unspent inputs from address ..." but inputs list is empty.

**Comment by tbak42** [comment]
I can confirm that this now happens to me as well.

It appears to be because the API call to coinb.in/api will use http instead of https when running from a local source. The http calls are now getting redirected to https, which causes the ajax call to fail with no response.

I was able to fix this locally by editing coin.js to force the coinjs.host variable to always use https.

**Comment by OutCast3k** [comment]
I've allowed the use of non https traffic to the api, this should allow the existing code to function again but I will i will update the code later.

**Comment by tbak42** [comment]
Thanks. :)
